// Generated by scripts/gen-deployments.mjs from @meddleware/seal-policies-sui@0.0.7 — do not edit.
// Regenerate with `npm run gen:deployments` after bumping that package.

/** One network's `seal_policies` deployment. */
export interface SealPoliciesDeployment {
  /**
   * Package id the types and events are defined at (never changes across upgrades). Seal key
   * servers bind identities to it: encrypt under this id.
   */
  originalId: string
  /** Latest package version: the call target for `seal_approve*` and `sealed_content::publish`. */
  publishedAt: string
  /** The shared `PolicyConfig` (version gate) every `seal_approve*` and `publish` reads. */
  policyConfigId: string
}

/** Every recorded `seal_policies` deployment, by network. */
export const SEAL_POLICIES_DEPLOYMENTS = {
  testnet: {
    originalId: '0x0c8f73490b14836e6a7a724fb46b242cb061d04a5f193fd637159997f8a1773d',
    publishedAt: '0x0c8f73490b14836e6a7a724fb46b242cb061d04a5f193fd637159997f8a1773d',
    policyConfigId: '0xee0403ba15c250223527150d147f29bedfb1ec46bb2282c341be462ff0ad7d1a',
  },
} as const satisfies Record<string, SealPoliciesDeployment>

export type SealPoliciesNetwork = keyof typeof SEAL_POLICIES_DEPLOYMENTS

/**
 * The `seal_policies` deployment on `network`.
 *
 * @throws {Error} if there is no deployment recorded for `network`.
 */
export function sealPoliciesDeployment(network: string): SealPoliciesDeployment {
  const deployment = Object.hasOwn(SEAL_POLICIES_DEPLOYMENTS, network) ? (SEAL_POLICIES_DEPLOYMENTS as Record<string, SealPoliciesDeployment>)[network] : undefined
  if (!deployment) throw new Error(`no seal_policies deployment recorded for ${network}`)
  return deployment
}
