// Generated by scripts/gen-deployments.mjs from @meddleware/seal-policies-sui@0.0.6 — do not edit.
// Regenerate with `npm run gen:deployments` after bumping that package.

/** One network's `seal_policies` deployment. */
export interface SealPoliciesDeployment {
  /**
   * Package id the types and events are defined at (never changes across upgrades). Seal key
   * servers bind identities to it: encrypt under this id.
   */
  originalId: string
  /** Latest package version: the call target for `seal_approve*` and `sealed_content::publish`. */
  publishedAt: string
  /** The shared `PolicyConfig` (version gate) every `seal_approve*` and `publish` reads. */
  policyConfigId: string
}

/** Every recorded `seal_policies` deployment, by network. */
export const SEAL_POLICIES_DEPLOYMENTS = {
  testnet: {
    originalId: '0x61c4aaa431cc33a41a9db34621e2925fc8eb4e3b3f1d70eaeb8d8c2b73507e42',
    publishedAt: '0x61c4aaa431cc33a41a9db34621e2925fc8eb4e3b3f1d70eaeb8d8c2b73507e42',
    policyConfigId: '0xa5013eb407cac7e48b0b7f1cb5540b0e6115566dd01988b8f11fe77f4ebf3595',
  },
} as const satisfies Record<string, SealPoliciesDeployment>

export type SealPoliciesNetwork = keyof typeof SEAL_POLICIES_DEPLOYMENTS

/**
 * The `seal_policies` deployment on `network`.
 *
 * @throws {Error} if there is no deployment recorded for `network`.
 */
export function sealPoliciesDeployment(network: string): SealPoliciesDeployment {
  const deployment = (SEAL_POLICIES_DEPLOYMENTS as Record<string, SealPoliciesDeployment>)[network]
  if (!deployment) throw new Error(`no seal_policies deployment recorded for ${network}`)
  return deployment
}
