// Generated by scripts/gen-deployments.mjs from @meddleware/seal-policies-sui@0.0.5 — do not edit.
// Regenerate with `npm run gen:deployments` after bumping that package.

/** One network's `seal_policies` deployment. */
export interface SealPoliciesDeployment {
  /**
   * Package id the types and events are defined at (never changes across upgrades). Seal key
   * servers bind identities to it: encrypt under this id.
   */
  originalId: string
  /** Latest package version: the call target for `seal_approve*` and `sealed_content::publish`. */
  publishedAt: string
}

/** Every recorded `seal_policies` deployment, by network. */
export const SEAL_POLICIES_DEPLOYMENTS = {
  testnet: {
    originalId: '0x42cc181f851ef702c1fddc9b925553f03b71784edff49d80fbc260055f86d612',
    publishedAt: '0x8fcf9c39f35880c923fe811d7566d3f0352fc8b1d1c2652cac711810cb1f15cb',
  },
} as const satisfies Record<string, SealPoliciesDeployment>

export type SealPoliciesNetwork = keyof typeof SEAL_POLICIES_DEPLOYMENTS

/**
 * The `seal_policies` deployment on `network`.
 *
 * @throws {Error} if there is no deployment recorded for `network`.
 */
export function sealPoliciesDeployment(network: string): SealPoliciesDeployment {
  const deployment = (SEAL_POLICIES_DEPLOYMENTS as Record<string, SealPoliciesDeployment>)[network]
  if (!deployment) throw new Error(`no seal_policies deployment recorded for ${network}`)
  return deployment
}
